spring:
  datasource:
     url: jdbc:mysql://192.168.17.92:3306/qyb_test?characterEncoding=UTF-8
     username: test
     password: 589984646
     driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
      prefix: classpath:/templates/

mybatis:
  type-aliases-package: com.jovan.bean
#  mapper-locations: mybatis-config.xml


