server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://10.10.9.27:3306/ct?useUnicode=true&characterEncoding=UTF-8
    username: zjgg
    password: zjgg123
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/


dubbo:
  application:
    name: spring-boot-user-provider
  registry:
    address: zookeeper://10.10.9.25:2181