spring:
  datasource:
     url: jdbc:mysql://192.168.17.92:3306/qyb_test?characterEncoding=UTF-8
     username: test
     password: 123456
     driver-class-name: com.mysql.jdbc.Driver



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jovan.bean
  config-location: classpath:mybatis-config.xml


#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql





