spring:
  datasource:
    url: jdbc:mysql://10.10.9.27:3306/ct?useUnicode=true&characterEncoding=UTF-8
    username: zjgg
    password: zjgg123
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  #实体类所做包
  type-aliases-package: com.jovan.model.Person
  #mapper.xml所在位置
  mapper-locations: classpath:mappers/*.xml

dubbo:
  application:
    name: spring-boot-user-provider
  registry:
    address: zookeeper://10.10.9.25:2181
  protocol:
    name: dubbo
    port: 20880

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level.com.jovan.dao : debug
